image: jekyll/minimal:3

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
    - jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
