image: alpine:latest

pages:
  stage: deploy
  script:
    - cat .gitlab-ignore | xargs rm
    - mkdir .public
    - mv * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
