image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - mkdir .public
    - mv * .public
    - mv .well-known .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
