image: alpine:latest

pages:
  stage: deploy
  script:
    - git submodule update --init --recursive --remote
    - mkdir .public
    - mv * .public
    - mv .well-known .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
