source: .
destination: .public
layouts_dir: .layout
data_dir: .data
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  post:
    output: true
    permalink: /:collection/:name
    layout: "post"
permalink: pretty
exclude:
  - functions
  - database.rules.json
  - firebase.json
  - package.json
  - package-lock.json
kramdown:
  hard_wrap: true
incremental: true
host: 0.0.0.0
port: 8000
